### PR TITLE
add privacy statement checkbox to endorsement form

### PR DESCRIPTION
**Pull request by Tommos0**

### CODE REVIEW

**Comment by Tommos0** [comment]
fixes #28

**Comment by mkuzak** [comment]
thank you.
It looks like the checkbox and `Agree` are overlapping. I'm on Safari.

**Comment by mkuzak** [comment]
awesome, thank you. It looks like the checkbox and text are misaligned, at least on Safari.
Screenshot 2020-02-06 at 15 06 01

**Comment by Tommos0** [comment]
@mkuzak , I've updated some CSS, can you try again? (I don't have Safari).

**Comment by mkuzak** [comment]
thank you, looks good

**Pull request merged**
