### PR TITLE
Update email address

### PR DESCRIPTION
**Pull request by c-martinez**
We should email fairsoftware instead of info.

### CODE REVIEW

**Comment by c-martinez** [comment]
Ugly capitalization can be changed. `fair-software` would indeed be more consistent, but I think the office group was already created as `fairsoftware` and I am not sure if it can be changed.

**Comment by jspaaks** [comment]
Even if we can't change the name of the office group that does not seem like a valid reason to me.

**Comment by c-martinez** [comment]
What do you suggest?

**Comment by jspaaks** [comment]
This suggests magic PowerShell commands 
https://techcommunity.microsoft.com/t5/office-365-groups/renaming-of-o365-groups/m-p/4758

Or, I can make a copy of the existing office group and delete the old one?

**Comment by c-martinez** [comment]
Except Netlify already has fairsoftware@esciencecenter.nl as registered email address.

**Comment by jspaaks** [comment]
fairsoftware@esciencecenter.nl is shall remain then

**Comment by c-martinez** [comment]
Fixed ugly capitalization.

**Pull request merged**
